### ISSUE TITLE
12 Unit tests fail on Win7

### ISSUE THREAD

**Issue by almostautomated** [npp-community/npp-community#1]
There seems to be a difference causing test failures when using Win7 shlwapi.dll 6.1.7100.  These tests pass fine using shlwapi.dll 6.00.2900.5512

2>[  PASSED  ] 124 tests.
2>[  FAILED  ] 12 tests, listed below:
2>[  FAILED  ] PathAppendTest.ParentBasedBasicPathAndBasicName
2>[  FAILED  ] PathAppendTest.ParentBasedFullPathAndBasicName
2>[  FAILED  ] PathAppendTest.ParentBasedBasicPathAndRootPath
2>[  FAILED  ] PathAppendTest.ParentBasedFullPathAndRootPath
2>[  FAILED  ] PathAppendTest.ParentOfTwoDeepPathBackOneParentAndBasicName
2>[  FAILED  ] PathRemoveFileSpecTest.BasicPathNoFileDoubleMiddleSlashWithoutEndSlash
2>[  FAILED  ] PathCanonicalizeTest.ParentOverflow
2>[  FAILED  ] PathCanonicalizeTest.ParentParentOverflow
2>[  FAILED  ] PathCanonicalizeTest.SameParentOverflow
2>[  FAILED  ] PathCanonicalizeTest.SameParentParentOverflow
2>[  FAILED  ] PathCanonicalizeTest.ParentSameOverflow
2>[  FAILED  ] PathCanonicalizeTest.ParentSameParentOverflow
2>12 FAILED TESTS

**Comment by npp-community** [comment]
A msdn forum thread has been opened on this issue at:

http://social.msdn.microsoft.com/Forums/en-US/vcprerelease/thread/0ccc6b91-4a5e-42c6-96de-be052e7049d9

**Comment by almostautomated** [comment]
Moved ticket to lighthouse issue#4
